"""Obsidian Wiki Vault — generates and maintains a project wiki as plain markdown.

Auto-generates an Obsidian-compatible vault with [[wikilinks]] containing:
- Home index page
- Species lore pages (from SPECIES_CATALOG)
- Architecture pages (from code_map scanner)
- Decision log pages (from .claude/rules/decisions.md)
- Session journal entries (from session observer)
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from buddies.core.code_map import scan_project, FileInfo
from buddies.core.buddy_brain import SPECIES_CATALOG, Species, Rarity, EVOLUTION_STAGES


VAULT_DIR_NAME = ".buddy-wiki"


@dataclass
class VaultStats:
    """Summary of what the vault contains."""
    vault_path: Path
    session_count: int = 0
    species_count: int = 0
    module_count: int = 0
    decision_count: int = 0
    last_updated: float = 0.0
    exists: bool = False


class ObsidianVault:
    """Generates and maintains an Obsidian-compatible wiki vault."""

    def __init__(self, project_path: Path | None = None):
        self.project_path = project_path or Path.cwd()
        self.vault_path = self.project_path / VAULT_DIR_NAME

    def get_stats(self) -> VaultStats:
        """Scan existing vault and return stats without writing anything."""
        stats = VaultStats(vault_path=self.vault_path)

        if not self.vault_path.exists():
            return stats

        stats.exists = True

        # Count session journals
        sessions_dir = self.vault_path / "sessions"
        if sessions_dir.exists():
            stats.session_count = len(list(sessions_dir.glob("*.md")))

        # Count species pages
        species_dir = self.vault_path / "species"
        if species_dir.exists():
            # Subtract 1 for the index page
            pages = list(species_dir.glob("*.md"))
            stats.species_count = max(0, len(pages) - 1)

        # Count module pages
        modules_dir = self.vault_path / "architecture" / "modules"
        if modules_dir.exists():
            stats.module_count = len(list(modules_dir.glob("*.md")))

        # Count decision pages
        decisions_dir = self.vault_path / "decisions"
        if decisions_dir.exists():
            pages = list(decisions_dir.glob("*.md"))
            stats.decision_count = max(0, len(pages) - 1)

        # Last updated
        home = self.vault_path / "Home.md"
        if home.exists():
            stats.last_updated = home.stat().st_mtime

        return stats

    def generate_full(self) -> VaultStats:
        """Regenerate the entire vault from scratch."""
        self._ensure_dirs()
        self._write_gitignore()
        self.generate_species_pages()
        self.generate_architecture_pages()
        self.generate_decisions_pages()
        self.generate_home()
        return self.get_stats()

    def generate_home(self) -> None:
        """Write the Home.md index page with links to all sections."""
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        stats = self.get_stats()

        lines = [
            "# Buddies Wiki",
            "",
            f"*Auto-generated by Buddies — last updated {now}*",
            "",
            "## Sections",
            "",
            f"- [[species-index|Species Catalog]] — {len(SPECIES_CATALOG)} species across {len(Rarity)} rarities",
            f"- [[project-map|Architecture Map]] — project structure and dependencies",
            f"- [[dependency-graph|Dependency Graph]] — internal import relationships",
            f"- [[decisions-index|Architecture Decisions]] — why things are built this way",
            "",
            "## Sessions",
            "",
        ]

        # List recent session journals (newest first, max 10)
        sessions_dir = self.vault_path / "sessions"
        if sessions_dir.exists():
            journals = sorted(sessions_dir.glob("*.md"), reverse=True)[:10]
            if journals:
                for j in journals:
                    name = j.stem
                    lines.append(f"- [[{name}]]")
            else:
                lines.append("*No session journals yet — they're created when you close Buddies.*")
        else:
            lines.append("*No session journals yet.*")

        lines.extend([
            "",
            "## Quick Stats",
            "",
            f"- Species pages: {stats.species_count}",
            f"- Module pages: {stats.module_count}",
            f"- Decision pages: {stats.decision_count}",
            f"- Session journals: {stats.session_count}",
            "",
            "---",
            "*Open this folder in [Obsidian](https://obsidian.md) to navigate with wikilinks.*",
        ])

        self._write_page("Home.md", "\n".join(lines))

    def generate_species_pages(self) -> int:
        """Generate species-index.md + one page per species. Returns count."""
        self._ensure_dirs()

        # Group by rarity
        by_rarity: dict[Rarity, list[Species]] = {}
        for sp in SPECIES_CATALOG:
            by_rarity.setdefault(sp.rarity, []).append(sp)

        # Index page
        lines = [
            "# Species Catalog",
            "",
            f"*{len(SPECIES_CATALOG)} species across {len(Rarity)} rarities.*",
            "",
        ]

        for rarity in Rarity:
            species_list = by_rarity.get(rarity, [])
            pct = {
                Rarity.COMMON: "40%", Rarity.UNCOMMON: "30%",
                Rarity.RARE: "18%", Rarity.EPIC: "9%", Rarity.LEGENDARY: "3%",
            }.get(rarity, "?%")

            lines.append(f"## {rarity.value.title()} ({pct}) — {len(species_list)} species")
            lines.append("")
            lines.append("| Species | Emoji | Description |")
            lines.append("|---------|-------|-------------|")
            for sp in species_list:
                lines.append(f"| [[{sp.name}]] | {sp.emoji} | {sp.description} |")
            lines.append("")

        lines.extend(["---", "Back to [[Home]]"])
        self._write_page("species/species-index.md", "\n".join(lines))

        # Individual species pages
        count = 0
        for sp in SPECIES_CATALOG:
            self._write_page(
                f"species/{sp.name}.md",
                self._species_page_content(sp),
            )
            count += 1

        return count

    def generate_architecture_pages(self) -> int:
        """Generate project-map, dependency-graph, and per-module pages. Returns module count."""
        self._ensure_dirs()
        files = scan_project(self.project_path)

        if not files:
            self._write_page("architecture/project-map.md", "# Project Map\n\nNo source files found.\n")
            return 0

        # Group files by directory
        dirs: dict[str, list[FileInfo]] = {}
        for f in files:
            dir_name = str(Path(f.rel_path).parent).replace("\\", "/")
            if dir_name == ".":
                dir_name = "root"
            dirs.setdefault(dir_name, []).append(f)

        # Project map page
        map_lines = [
            "# Project Map",
            "",
            f"*{len(files)} files indexed.*",
            "",
        ]

        for dir_name in sorted(dirs.keys()):
            dir_files = dirs[dir_name]
            slug = self._slugify(dir_name)
            map_lines.append(f"### [[{slug}|{dir_name}/]]")
            for f in dir_files:
                desc = f" — {f.description}" if f.description else ""
                map_lines.append(f"- `{Path(f.rel_path).name}` ({f.line_count}L){desc}")
            map_lines.append("")

        map_lines.extend(["---", "See also: [[dependency-graph]] | Back to [[Home]]"])
        self._write_page("architecture/project-map.md", "\n".join(map_lines))

        # Dependency graph page
        code_files = [f for f in files if f.imports]
        dep_lines = [
            "# Dependency Graph",
            "",
            "Internal import relationships between modules.",
            "",
        ]
        if code_files:
            for f in code_files:
                deps = ", ".join(sorted(set(f.imports)))
                dep_lines.append(f"- `{f.rel_path}` imports: {deps}")
        else:
            dep_lines.append("*No internal imports detected.*")

        dep_lines.extend(["", "---", "See also: [[project-map]] | Back to [[Home]]"])
        self._write_page("architecture/dependency-graph.md", "\n".join(dep_lines))

        # Per-module pages
        module_count = 0
        for dir_name, dir_files in dirs.items():
            slug = self._slugify(dir_name)
            self._write_page(
                f"architecture/modules/{slug}.md",
                self._module_page_content(dir_name, dir_files),
            )
            module_count += 1

        return module_count

    def generate_decisions_pages(self) -> int:
        """Parse decisions.md into individual pages. Returns count."""
        self._ensure_dirs()
        decisions = self._parse_decisions()

        # Index page
        lines = [
            "# Architecture Decisions",
            "",
            f"*{len(decisions)} decisions documented.*",
            "",
        ]

        if decisions:
            for d in decisions:
                slug = self._slugify(d["title"])
                lines.append(f"- [[{slug}|{d['title']}]]")
        else:
            lines.append("*No decisions found. Add them to `.claude/rules/decisions.md`.*")

        lines.extend(["", "---", "Back to [[Home]]"])
        self._write_page("decisions/decisions-index.md", "\n".join(lines))

        # Individual decision pages
        count = 0
        for d in decisions:
            slug = self._slugify(d["title"])
            page_lines = [
                f"# {d['title']}",
                "",
                d["body"],
                "",
                "---",
                "Back to [[decisions-index|Architecture Decisions]] | [[Home]]",
            ]
            self._write_page(f"decisions/{slug}.md", "\n".join(page_lines))
            count += 1

        return count

    def write_session_journal(
        self,
        stats,
        convo_messages: list[dict] | None = None,
    ) -> Path | None:
        """Write a new session journal entry. Called at session end."""
        if not self.vault_path.exists():
            return None

        self._ensure_dirs()
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M")

        # Find next session number for today
        sessions_dir = self.vault_path / "sessions"
        existing = list(sessions_dir.glob(f"{date_str}_session-*.md"))
        session_num = len(existing) + 1

        filename = f"{date_str}_session-{session_num:03d}.md"

        duration = f"{stats.duration_minutes:.0f} min" if stats.duration_minutes > 0 else "unknown"

        lines = [
            f"# Session — {date_str} #{session_num}",
            "",
            f"**Time**: {time_str} | **Duration**: {duration}",
            "",
            "## Stats",
            "",
            f"- Events: {stats.event_count}",
            f"- Tokens (est.): {stats.tokens_estimated:,}",
            f"- Files touched: {len(stats.files_touched)}",
            f"- Edits: {stats.edit_count}",
            f"- Most used tool: {stats.most_used_tool}",
        ]

        if stats.current_model:
            lines.append(f"- Model: {stats.current_model}")

        # Tool breakdown
        if stats.tool_counts:
            lines.extend(["", "## Tools Used", ""])
            for tool, count in stats.tool_counts.most_common(10):
                lines.append(f"- {tool}: {count}")

        # Files touched
        if stats.files_touched:
            lines.extend(["", "## Files Touched", ""])
            for f in sorted(stats.files_touched):
                short = self._short_path(f)
                lines.append(f"- `{short}`")

        # Conversation highlights (last 20 user messages)
        if convo_messages:
            user_msgs = [m for m in convo_messages if m.get("role") == "user"]
            if user_msgs:
                lines.extend(["", "## Conversation Highlights", ""])
                for msg in user_msgs[-20:]:
                    text = msg.get("content", "")[:120]
                    lines.append(f"- {text}")

        lines.extend(["", "---", "Back to [[Home]]"])

        path = self._write_page(f"sessions/{filename}", "\n".join(lines))
        return path

    def sync_handoff(self) -> None:
        """Copy HANDOFF.md into the vault if it exists."""
        if not self.vault_path.exists():
            return

        handoff = self.project_path / "HANDOFF.md"
        if handoff.exists():
            content = handoff.read_text(encoding="utf-8", errors="replace")
            self._write_page("HANDOFF.md", content)

    # --- Private helpers ---

    def _ensure_dirs(self) -> None:
        """Create vault subdirectories if missing."""
        for subdir in ("sessions", "species", "architecture/modules", "decisions"):
            (self.vault_path / subdir).mkdir(parents=True, exist_ok=True)

    def _write_gitignore(self) -> None:
        """Create .gitignore in the vault so it's not accidentally committed."""
        gi_path = self.vault_path / ".gitignore"
        if not gi_path.exists():
            gi_path.write_text("# Auto-generated vault — not meant for version control\n*\n", encoding="utf-8")

    def _slugify(self, text: str) -> str:
        """Slugify for filenames."""
        slug = text.lower().replace("\\", "/").replace("/", "-").replace(" ", "-")
        slug = re.sub(r"[^a-z0-9\-_]", "", slug)
        slug = re.sub(r"-+", "-", slug).strip("-")
        return slug or "untitled"

    def _write_page(self, rel_path: str, content: str) -> Path:
        """Write a markdown page to the vault. Creates parent dirs."""
        full_path = self.vault_path / rel_path.replace("/", "\\") if "\\" in str(self.vault_path) else self.vault_path / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")
        return full_path

    def _species_page_content(self, species: Species) -> str:
        """Generate markdown content for a single species lore page."""
        # Format base stats
        stats_str = ", ".join(f"{k}: {v}" for k, v in species.base_stats.items())

        # Rarity color hint
        rarity_badges = {
            Rarity.COMMON: "Common",
            Rarity.UNCOMMON: "Uncommon",
            Rarity.RARE: "Rare",
            Rarity.EPIC: "Epic",
            Rarity.LEGENDARY: "Legendary",
        }

        lines = [
            f"# {species.name.replace('_', ' ').title()} {species.emoji}",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Rarity | {rarity_badges.get(species.rarity, species.rarity.value)} |",
            f"| Emoji | {species.emoji} |",
            f"| Base Stats | {stats_str} |",
            "",
            f"> {species.description}",
            "",
            "## Evolution Stages",
            "",
        ]

        for stage in EVOLUTION_STAGES:
            lines.append(f"- {stage['symbol']} **{stage['name']}** — Level {stage['min_level']}+")

        lines.extend([
            "",
            "## Related",
            "",
            "- [[species-index|Species Catalog]]",
            "- [[Home]]",
        ])

        return "\n".join(lines)

    def _module_page_content(self, dir_name: str, files: list[FileInfo]) -> str:
        """Generate markdown for a module/directory overview page."""
        lines = [
            f"# {dir_name}/",
            "",
            f"*{len(files)} files in this directory.*",
            "",
            "## Files",
            "",
        ]

        for f in files:
            desc = f" — {f.description}" if f.description else ""
            lines.append(f"### `{Path(f.rel_path).name}` ({f.line_count}L){desc}")
            lines.append("")

            if f.classes:
                lines.append(f"**Classes**: {', '.join(f.classes)}")
                lines.append("")
            if f.functions:
                lines.append(f"**Functions**: {', '.join(f.functions[:15])}")
                lines.append("")
            if f.imports:
                lines.append(f"**Imports**: {', '.join(sorted(set(f.imports)))}")
                lines.append("")

        lines.extend(["---", "Back to [[project-map|Project Map]] | [[Home]]"])
        return "\n".join(lines)

    def _parse_decisions(self) -> list[dict]:
        """Parse .claude/rules/decisions.md into structured decisions."""
        decisions_path = self.project_path / ".claude" / "rules" / "decisions.md"
        if not decisions_path.exists():
            return []

        content = decisions_path.read_text(encoding="utf-8", errors="replace")
        decisions = []

        # Parse bullet-point format: "- **Title** — body"
        for line in content.split("\n"):
            line = line.strip()
            match = re.match(r"^-\s+\*\*(.+?)\*\*\s*[—–-]\s*(.+)$", line)
            if match:
                decisions.append({
                    "title": match.group(1).strip(),
                    "body": match.group(2).strip(),
                })

        return decisions

    def _short_path(self, path: str) -> str:
        """Shorten a file path for display."""
        parts = path.replace("\\", "/").split("/")
        if len(parts) > 3:
            return "/".join(parts[-3:])
        return path
